### ISSUE TITLE
Add back button for going back to listview from contentview

### ISSUE THREAD

**Issue by leesera** [xhae/dwg-karrier#18]

**Comment by Juung** [comment]
Is this action should be same with "Finish Reading" button?

Let's talk about this later.

**Comment by Csoyee** [comment]
This occurs because list view activity call finish() before go to content view.

I'll change it as this is related to time calculation.

**Comment by Juung** [comment]
okay thanks!

**Comment by Juung** [comment]
@leesera Finished! (Please close this issue)
